sudo: requried
services:
 - docker

before_install:
 - docker build -t adinepstein/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true adinepstein/docker-react npm run test

deploy:
 provider: elasticbeanstalk
 region: "eu-west-2"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-eu-west-2-860548453892"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY

